name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install dependencies
      run: sudo apt install cppcheck valgrind
    - name: check statically
      run: cppcheck src
    - name: configure
      run: cmake .
    - name: make
      run: make
    - name: make test
      run: make test
    - name: check leaks
      run: valgrind --leak-check=full bin/hello 
